id: opecha:P009525
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS17287
  title: གྲུབ་མཐའི་རྣམ་བཞག་འཁྲུལ་སྤོང་གདོང་ལྔའི་སྒྲ་དབྱངས་ཀུན་མཁྱེན་ལམ་བཟང་གསལ་བའི་རིན་ཆེན་སྒྲོན་མེ།
  volume: ''
  author: ''
