id: IA49649D5
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T16:50:40+00:00'
last_modified: '2022-06-08T11:39:00.872164+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS17287
  title: གྲུབ་མཐའི་རྣམ་བཞག་འཁྲུལ་སྤོང་གདོང་ལྔའི་སྒྲ་དབྱངས་ཀུན་མཁྱེན་ལམ་བཟང་གསལ་བའི་རིན་ཆེན་སྒྲོན་མེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    00A8:
      image_group_id: I8LS17304
      title: ''
      total_pages: 440
      order: 1
      base_file: 00A8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
